### ISSUE TITLE
[BUG] Custom Home Logo 

### ISSUE THREAD

**Issue by C0D6WasTaken** [finnjosten/Zelk-Discord-Theme-Fixes#42]
The custom home logo broke with recent updates. Here's the code for quick testing.
```css
/* Change Home Screen Discord Logo */
.wrapper_d281dd[ data-list-item-id="guildsnav___home"] .childWrapper__01b9c path {
    fill: transparent;
}

.wrapper_d281dd[ data-list-item-id="guildsnav___home"] .childWrapper__01b9c {
    --home-icon: url('https://r2.e-z.host/b4a4c775-45ca-4ccf-9e8b-a6e14f598ee1/sxa6o56y.png');
    background: var(--home-icon) center/contain no-repeat;
    width: 48px;
    height: 48px;
}
```
